#!/bin/bash
echo "Hi everybody
Would you like this bot (y/n)?"
read answer
[[ $answer =~ ^([yY][eE][sS]|[yY])$ ]]
echo "OK :) here you have http://github.com/iicc1/TgBash"
echo "OK then."
until [ "$SUCCESS" = "y" ] ;do
	echo 'Do you like the backgrounds? mykeyboardstartshere "Yes" "No"'
	read answer
	case $answer in
		'Yes') echo "Oh yeah, me also, here you have http://www.solofondosdepantalla.net/fondos-de-pantalla/Abstractos/Fondo-de-pantalla-Abstracto-210.jpg ";SUCCESS=y;;
		'No') echo "Oh, you are weird";SUCCESS=y;;
		*) SUCCESS=n;;
	esac
done
exit
